name: MacOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: prepare
      run: |
        brew install gettext autoconf automake libiconv libtool \
                    gs graphicsmagick python xmlto pkg-config ccache

        brew unlink libtool && brew link libtool
        brew unlink gettext && brew link gettext
    - name: configure
      run:
        export PATH="/usr/local/opt/libiconv/bin:$PATH"
        export PATH="/usr/local/opt/ccache/libexec:$PATH"
        export LDFLAGS="-L/usr/local/opt/libiconv/lib"
        export CPPFLAGS="-I/usr/local/opt/libiconv/include"

        autoreconf -vfi

        ./configure --disable-video --without-qt --without-gtk --disable-nls --with-python=python3 --without-imagemagick --with-graphicsmagick

    - name: build
      run: |
        make
        sudo make install
