# Should run only on branches and PR, as "on_tag.yml" will handle tags
on:
  push:
    branches: master test
  pull_request:
    branches: master
  workflow_dispatch:

jobs:

#
# Windows
#
  Windows:
    name: Windows
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [x86_64]
        video: [VfW]
        include:
          - arch: x86_64
            msystem: MINGW64
            grep: x86-64
          - video: VfW
            extra:
    defaults:
      run:
        shell: msys2 {0}

    env:
      CPPFLAGS: -D__USE_MINGW_ANSI_STDIO=1

    steps:
    - uses: msys2/setup-msys2@v2
      with:
        msystem: ${{ matrix.msystem }}
        update: false
        install: >-
          mingw-w64-${{ matrix.arch }}-gcc
          mingw-w64-${{ matrix.arch }}-iconv
          mingw-w64-${{ matrix.arch }}-imagemagick
          mingw-w64-${{ matrix.arch }}-python
          base-devel git xmlto zip
          autoconf libtool automake gettext make autoconf-archive pkg-config docbook-xsl

    - uses: actions/checkout@v2

    - name: configure
      shell: msys2 {0}
      run: |
        autoreconf -vfi
        ./configure LDFLAGS="-static" --with-x=no --enable-video=yes --with-jpeg=no --with-directshow=yes --disable-dependency-tracking ${{ matrix.extra }}

    - name: build
      shell: msys2 {0}
      run:
        make

    - name: generating zip
      shell: msys2 {0}
      run: |
        DESTDIR=${PWD}/win_${{ matrix.arch }}-${{ matrix.video }} make install
        (cd ${PWD}/win_${{ matrix.arch }}-${{ matrix.video }}; zip -r ../zbar-win_${{ matrix.arch }}-${{ matrix.video }}.zip .)
        cd ..

    - name: generating sha256 hash
      shell: msys2 {0}
      run:
        sha256sum zbar-win_${{ matrix.arch }}-${{ matrix.video }}.zip > hashes.txt

    - name: upload windows artifact
      uses: actions/upload-artifact@v3
      with:
        name: zbar-win_${{ matrix.arch }}-${{ matrix.video }}
        path: ./zbar-win_${{ matrix.arch }}-${{ matrix.video }}.zip

    - name: upload windows artifact
      uses: actions/upload-artifact@v3
      with:
        name: hashes
        path: ./hashes.txt

    - name: upload windows artifact
      uses: actions/upload-artifact@v3
      with:
        name: hashes
        path: ./include/config.h
